normal:
  up: cursor::move_up
  down: cursor::move_down
  left: cursor::move_left
  right: cursor::move_right
  j: cursor::move_down
  k: cursor::move_up
  h: cursor::move_left
  l: cursor::move_right
  q: buffer::close
  F: buffer::close_others
  J: cursor::move_to_last_line
  K: cursor::move_to_first_line
  H: cursor::move_to_start_of_line
  L: cursor::move_to_end_of_line
  b: cursor::move_to_start_of_previous_token
  w: cursor::move_to_start_of_next_token
  e: cursor::move_to_end_of_current_token
  a: cursor::append_to_current_token
  I: cursor::insert_at_first_word_of_line
  A: cursor::insert_at_end_of_line
  o: curso